[project]
authors = ["Antonio Camargo <antoniop.camargo@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Clusters sequences from a multiple sequence alignment (MSA) into distinct groups"
name = "cluster-msa"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11.10,<4"
numpy = ">=2.1.2,<3"
polyleven = ">=0.8,<0.9"
scikit-learn = ">=1.5.2,<2"
